dataset: /nfs/diskstation/projects/dex-net/regrasping/datasets/stp_10_09_17/tensors
x_names:
  - rgbd_ims
y_name: cur_stp_id
model_dir: /nfs/diskstation/projects/dex-net/regrasping/models/classification/

data_augmentation:
  featurewise_center: 1
  featurewise_std_normalization: 1

  image_shape:
    - 224
    - 224
    - 3  

  width_shift_range: 0.1
  height_shift_range: 0.1
  rotation_range: 180
  zoom_range: 0

  image_dropout_rate: 0.0
  image_gaussian_sigma: 5.0
  image_gaussian_corrcoef: 4
  rot_180: 0

  data_dropout_rate: 0.0
  data_gaussian_sigma: 0.000001

  horizontal_flip: 0
  vertical_flip: 0

preprocessing:
  augment: 1
  rounds: 5
  num_tensors: 100

data_iteration:
  shuffle: 1
  save_to_dir: 0
  save_prefix: iter
  save_format: png

model:
  base:
      model: /nfs/diskstation/projects/dex-net/models/classification/resnet50_notop
      type: resnet50
      params:
        include_fc: 0

  params:
    new_fc_layer_sizes:
      - 128

optimization:
  optimizer: adam
  lr: 0.001
  momentum: 0.9
  loss: categorical_crossentropy
  metrics:
    - accuracy

training:
  epochs: 10
  class_weight: auto
  use_multiprocessing: 1

  batch_size: 128
  train_pct: 0.9
  model_save_period: 1

debug: 0