# REGISTRATION PARAMS
chessboard_registration:
  corners_x: 6 # number of corners in the x direction
  corners_y: 9 # number of corners in the y direction
  num_transform_avg: 5 # number corner detections to average together
  num_images: 5 # number of depth images to take median of for noise reduction
  color_image_rescale_factor: 4.0 # rate to upsame the color image for detections
  
  # VISUALIZATION PARAMS
  vis: False # visualize registration
  debug: 1 # show the final pose detectoin
  scale_amt: 0.1 # scale for vis axes

calib_dir: /home/autolab/Public/alan/calib # directory for the output
objects_dir: /home/autolab/Public/alan/meshes # directory to look for the meshes

vis: True

# SENSOR CALIBRATION LIST
sensor:
   frame_name: primesense_overhead
   auto_white_balance: 0
   type: primesense
#sensor:
#    frame_name: kinect2_overhead 
#    device_num: 0
#    type: kinect2