name: Run Tests

on: [pull_request, workflow_dispatch]

jobs:
  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Formatting
      run: |
        pip install autopep8 flake8
    - name: Check Formatting
      run: |
        flake8 --config=.flake8 .
        echo ${{github.ref}}
        flake8 --config=.flake8 .
        autopep8 --recursive --aggressive --diff --exit-code ros_nodes/
        autopep8 --recursive --aggressive --diff --exit-code perception/
        autopep8 --recursive --aggressive --diff --exit-code tools/
        autopep8 --recursive --aggressive --diff --exit-code tests/

  tests:
    name: Run Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.5, 3.8]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Nose2
      run: |
        python -m pip install --upgrade pip
        pip install nose2
    - name: Install Perception
      run: pip install .
    - name: Run Nose Tests
      run: nose2